# Generated by Django 5.0.2 on 2024-02-20 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0002_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expDateTime', models.DateTimeField()),
                ('paymentMethod', models.CharField(choices=[('crediCard', 'crediCard'), ('cash', 'cash'), ('cheque', 'cheque'), ('UPI', 'UPI')], max_length=50)),
                ('status', models.CharField(choices=[('cleared', 'cleared'), ('uncleared', 'uncleared'), ('void', 'void')], max_length=255)),
                ('description', models.TextField()),
                ('transactionType', models.CharField(max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expense.category')),
                ('subCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expense.subcategory')),
            ],
            options={
                'db_table': 'expense',
            },
        ),
    ]
