# Generated by Django 5.0.2 on 2024-03-05 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0008_books'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goalName', models.CharField(max_length=100)),
                ('maxAmount', models.PositiveIntegerField()),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('status', models.CharField(choices=[('active', 'active'), ('paused', 'paused'), ('not-active', 'voinot-active')], max_length=100)),
            ],
            options={
                'db_table': 'expGoal',
            },
        ),
        migrations.AddField(
            model_name='expense',
            name='goal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='expense.expensegoal'),
        ),
    ]
